# Generated by Django 4.1.4 on 2022-12-31 17:30

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_song"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "image",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/media"
                        ),
                        upload_to="",
                    ),
                ),
            ],
        ),
    ]
