# Generated by Django 4.1.4 on 2022-12-31 17:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(location="/media"),
                upload_to=django.core.files.storage.FileSystemStorage(
                    location="/media"
                ),
            ),
        ),
    ]
