# Generated by Django 4.1.4 on 2023-01-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="personinfo",
            name="road_no",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
