# Generated by Django 4.1.4 on 2023-01-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_personinfo_road_no"),
    ]

    operations = [
        migrations.RemoveField(model_name="personinfo", name="road_no",),
    ]
