# Generated by Django 4.1.5 on 2023-01-12 16:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_mymodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "image",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/my_photo/"
                        ),
                        upload_to="",
                    ),
                ),
            ],
        ),
    ]
