# Generated by Django 4.1.5 on 2023-01-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="file",
            field=models.FileField(upload_to="employee_image/"),
        ),
    ]
